### PR TITLE
added apolloClient option for passing a preconfigured client

### PR DESCRIPTION
**Pull request by toadkicker**
This adds `context.options.apolloClient` to the available options so that developers can instantiate their own client and pass it to the plugin.

### CODE REVIEW

**Comment by phortx** [comment]
Thank you very much for your contribution! :)

I just have two things, we should change:

1. We then can drop the `options.link` option, because it's part of the client.
2. The client should be setup within a function, because to properly setup a client, you need the context. Like this:

```
const options = {
  apolloClient: (context) => {
    return ...;
  }
};
```

**Comment by toadkicker** [comment]
What if we change this to adding a `clients/DefaultClient` class, similar to how you approached the adapter problem?

**Comment by phortx** [comment]
This would force the user to write a wrapper class around the ApolloClient, which is too much here I think :)

**Comment by toadkicker** [comment]
This is how I'm setting it up in `store/index`, I'm not completely clear what you mean with passing context in the option:

```
import VuexORM from '@vuex-orm/core'
import AWSAppSyncClient from 'aws-appsync'
import { Auth } from 'aws-amplify'
import VuexORMGraphQL from '@vuex-orm/plugin-graphql'

import database from '../database'
import awsexports from '../aws-exports'

const options = {
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network'
    }
  },
  connectionQueryMode: 'nodes',
  database: database,
  url: awsexports.aws_appsync_graphqlEndpoint,
  includeExtensions: true,
  debug: process.env.NODE_ENV !== 'production'
}

const config = {
  url: awsexports.aws_appsync_graphqlEndpoint,
  region: awsexports.aws_appsync_region,
  auth: {
    type: awsexports.aws_appsync_authenticationType,
    jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken()
  }
}

const client = new AWSAppSyncClient(config, options)

options.apolloClient = client

VuexORM.use(VuexORMGraphQL, options)

export const plugins = [
  VuexORM.install(database)
]
```

**Comment by phortx** [comment]
> I'm not completely clear what you mean with passing context in the option:

Oh sorry, I think I didn't make that clear. In your implementation we pass the apollo client into the options as a instance of the client. But to properly setup a client, the developer could need the context. So I want to provide it. We can achieve that by changing how plugin-graphql accepts the client: not as a object, but by calling a function.

So changing your code how to setup a client it would work like this:

```js
import VuexORM from '@vuex-orm/core'
import AWSAppSyncClient from 'aws-appsync'
import { Auth } from 'aws-amplify'
import VuexORMGraphQL from '@vuex-orm/plugin-graphql'

import database from '../database'
import awsexports from '../aws-exports'

const options = {
  defaultOptions: {
    watchQuery: {
      fetchPolicy: 'cache-and-network'
    }
  },
  connectionQueryMode: 'nodes',
  database: database,
  url: awsexports.aws_appsync_graphqlEndpoint,
  includeExtensions: true,
  debug: process.env.NODE_ENV !== 'production'
}

// I changed this!
options.apolloClient =(contex) => {
    const config = {
    url: awsexports.aws_appsync_graphqlEndpoint,
    region: awsexports.aws_appsync_region,
    auth: {
      type: awsexports.aws_appsync_authenticationType,
      jwtToken: async () => (await Auth.currentSession()).getIdToken().getJwtToken()
    }
  };

  return new AWSAppSyncClient(config, options);
};

VuexORM.use(VuexORMGraphQL, options)

export const plugins = [
  VuexORM.install(database)
]
```

Also I think we then can drop the support for `options.link` completly

**Comment by toadkicker** [comment]
@phortx :+1: merge ready

**Comment by phortx** [comment]
Looks good :) Thank you very much for your contribution!

**Pull request merged**
