### PR TITLE
feat: compatibility with vue-orm-0.36

### PR DESCRIPTION
**Pull request by romtorres**
I wanted to use it with the last version of vue-orm so I updated it according to their new ORM Model. 
It's using Uid instead of increment.

It's the first time I made a PR so be indulgent please :) 

I tried to pass all tests but I had difficulties especially with how to add types to Objects, so please do not merge this PR yet

Example : `

    - Object {
    -   "users": Array [
    -     Object {
    + User {
        "$id": "42",
        "$isPersisted": true,
        "comments": Array [],
        "id": "42",
        "name": "Charlie Brown",
        "posts": Array [],
        "profile": null,
    -       "profileId": "$uid1",
    -     },
    -   ],
    +   "profileId": "$uid9",
      }
`

### CODE REVIEW

**Comment by phortx** [comment]
Hi! That's amazing! Thank you very much for tackling this difficult task.

I have started to upgrade the npm packages on my own, maybe the `feature/npm-upgrades` branch helps you? You can merge this branch into yours, I think, then we continue to work on it in your branch :)

**Comment by romtorres** [comment]
Thank you, I merged branches like you said.

I added some more tests to be compatible but I'm stuck with tests involving relations. 

I can't see for the Tariff one which field is making the relation between Tariff and tariffOptions.

`Many To Many Relation › works

    expect(received).not.toEqual(expected) // deep equality

    Expected: not 0

      19 |     expect(tariff.name).toEqual("Super DSL S");
      20 |     expect(tariff.tariffOptions).not.toEqual(null);
    > 21 |     expect(tariff.tariffOptions.length).not.toEqual(0);
         |                                             ^
      22 |     expect(tariff.tariffOptions[0].name).toEqual("Installation");
      23 |     expect(tariff.tariffOptions[0].tariffs).not.toEqual(null);
      24 |     expect(tariff.tariffOptions[0].tariffs[0].name).toEqual("Super DSL S");

      at test/integration/relations/many-to-many.spec.ts:21:45
      at step (test/integration/relations/many-to-many.spec.ts:33:23)
      at Object.next (test/integration/relations/many-to-many.spec.ts:14:53)
      at fulfilled (test/integration/relations/many-to-many.spec.ts:5:58)`

**Comment by phortx** [comment]
I fixed everything :) Thanks for your initiative!

**Comment by romtorres** [comment]
Perfect, thank you, you're welcome !

**Pull request merged**
