### PR TITLE
Allow GUIDs as primary key instead of just numbers (and fix typings)

### PR DESCRIPTION
**Pull request by timvandesteeg**
- `toNumber()` is only used to parse IDs, so I recommend changing it to `toPrimaryKey` and also allow GUIDs.
- also added the possibility to override the singularName or pluralName from the source Model
- and fixed the misconfigured typings from https://github.com/vuex-orm/plugin-graphql/issues/158

### CODE REVIEW

**Comment by phortx** [comment]
Hi @timvandesteeg ,

thank you very much for your contribution! :) 

Could you please provide tests for overwriting the singular/plural name and also for using GUIDs?

**Comment by timvandesteeg** [comment]
Added the tests :)
Compliments for this plugin by the way. Love the abstraction it provides!

**Comment by phortx** [comment]
Looks good :)

Thank you very much for the kind words. Would be nice when I'd have more time for this project :(

**Comment by phortx** [comment]
Releases as https://github.com/vuex-orm/plugin-graphql/releases/tag/v1.0.0-rc.42

**Pull request merged**
